# Generated by Django 3.1.5 on 2021-04-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price_per_size',
            new_name='price',
        ),
    ]
