# Generated by Django 3.1.5 on 2021-04-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210420_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='price_per_size',
        ),
    ]
